-# Site settings		
 -title: Pawel Cyrta
 -email: pawel@cyrta.com		
 -description: > # this means to ignore newlines until "baseurl:"		
 Personal page of Pawel Cyrta -- Speech &amp; Music Technology Researcher &amp; Composer, working with state-of-the-art machine learning algorithms and audio/sound content production, processing, analysis and distribution.
 -baseurl: "" # the subpath of your site, e.g. /blog/		
 -url: "http:/cyrta.com" # the base hostname & protocol for your site		
 -twitter_username: cyrta		
 -github_username:  cyrta		
 

